<link rel="stylesheet" type="text/css" href="<?php echo Atomik::asset('assets/css/index.css');?>">
<div class="row">
  <div class="col-sm-12 text-center" >
    <div class="btn-group">

      <?php if($page > 1):?>
        <a class="btn btn-info" href="<?php echo Atomik::url('index', array('page' => 1));?>"><<</a>
        <a class="btn btn-info" id="prec" href="<?php echo Atomik::url('index', array('page' => $page-1));?>"><</a>
        <a class="btn btn-info" href="<?php echo Atomik::url('index', array('page' => $page-1));?>"><?php echo $page-1;?></a>
      <?php endif ?>

      <a class="btn" href="#"><?php echo $row["titre"];?></a>

      <?php if ($page < $nbpages):?>
        <a class="btn btn-info" href="<?php echo Atomik::url('index', array('page' => $page+1));?>"><?php echo $page+1;?></a>
        <a class="btn btn-info" id="suiv" href="<?php echo Atomik::url('index', array('page' => $page+1));?>">></a>
        <a class="btn btn-info" href="<?php echo Atomik::url('index', array('page' => $nbpages));?>">>></a>
      <?php endif ?>

    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-10 col-sm-push-1 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3 text-right" >
    <img class="img-rounded" src="<?php echo Atomik::asset('assets/' . $row["url"]);?>">
    <span class="label label-default">le <?php echo $row["dateheure"];?> par <?php echo $row["auteur"];?></span>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function ()
  {
    var keys = {};

    $(window).on("keyup keydown", function (e) {
      e = e || event;
      keys[e.keyCode] = e.type === 'keydown';

      console.log(e.keyCode);

      //39=droite 74=j 78=n
      if (keys[39] || keys[74] || keys[78]) {
        $('#suiv').get(0).click();
      }
      //37=gauche 75=k 80=p
      else if (keys[37] || keys[75] || keys[80]) {
        $('#prec').get(0).click();
      }
    })
  });
</script>  
